vendor: Netease
name: Netease Qinqzhou MicroService
version: v1.0
website_url: https://www.163yun.com/product-nsf
documentation_url: https://www.163yun.com/help/documents/226572446484058112
product_logo_url: https://tools.nos-eastchina1.126.net/nsf/%E8%BD%BB%E8%88%9F%E5%BE%AE%E6%9C%8D%E5%8A%A1logo-02.png
type: distribution
description: Netease QingZhou Microservice is a one-stop PaaS platform built around applications and Microservice, which helps users to quickly realize easy access, easy operation and maintenance of Microservice solutions.
